#!/usr/bin/perl -w
use strict;
use warnings;

use LWP::UserAgent;
use URI::Escape;

## Get a certain URL
my $url = "http://www.sloganizer.net/en/outbound.php?slogan=";

my $ua = new LWP::UserAgent;

#Set agent name, we are not a script! :)
my $agent = "Mozilla/4.0 (compatible; MSIE 4.01; Windows 98)";
$ua->agent($agent);

my @args = @ARGV;
if (not @args or @args == 1 and $args[0] eq '' ) {
	my @options = (
			[ 'DND' ],
			[ 'frop' ],
			[ 'SNT' ],
			[ 'Multigate' ],
			[ 'WESP' ],
			[ 'Multilink' ],
			[ 'pietjepuk' ],
		);
	my $user = $ENV{'MULTI_REALUSER'};
	my $total = 50;
	my $index = int rand $total;
	@args = ( $index < scalar @options ? @{$options[$index]} : ( defined $user ? ($user) : ('pietjepuk') ) );
}

$url .= join '+', map { uri_escape($_) } @args;

my $request = new HTTP::Request( 'GET', $url );
my $content = $ua->request($request)->content;

if (defined $content) {
	my ($result) = $content =~ m#^\<a href='http://www.sloganizer.net/en/' title='Generated by Sloganizer.net' style='text-decoration:none;'\>(.*)\</a\>$#;
	# $result = HTML::Entities::decode($result);
	print $result, "\n";
} else {
	print "Internal error\n";
}
